# compose.yaml
services:
  # 開発用コンテナ
  # Rustの開発ができる
  yutai_watch_dev:
    container_name: yutai_watch_dev
    build:
      context: .
      dockerfile: .docker/dev/Dockerfile
    volumes:
      - .:/app
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target
      # configをvolume化(configを変更してもコンテナを再起動しなくても良くなる)
      - ./.config/app.dev.toml:/app/.config/app.toml
      - ./.config/.env.dev:/app/.config/.env
    # 作業用ディレクトリの指定
    working_dir: /app
    # 仮想端末を割り当てる？
    tty: true
    command: bash -c "cargo watch -x check"

  # 本番用コンテナ
  # Rustバイナリだけ入れる。
  # このコンテナを常駐させ、cronに定期実行させる。
  yutai_watch:
    container_name: yutai_watch
    build:
      context: .
      dockerfile: .docker/prod/Dockerfile
    restart: unless-stopped
    volumes:
      # configをvolume化(configを変更してもコンテナを再起動しなくても良くなる)
      - ./.config/app.prod.toml:/app/.config/app.toml
      - ./.config/.env.prod:/app/.config/.env

volumes:
  cargo_cache:
  target_cache:
